// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/raft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Raft FSM commands for state replication
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "submit_job", "assign_job", "complete_job", "register_worker", "remove_worker"
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Command payloads
type SubmitJobCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobCommand) Reset() {
	*x = SubmitJobCommand{}
	mi := &file_api_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobCommand) ProtoMessage() {}

func (x *SubmitJobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobCommand.ProtoReflect.Descriptor instead.
func (*SubmitJobCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobCommand) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type AssignJobCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJobCommand) Reset() {
	*x = AssignJobCommand{}
	mi := &file_api_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJobCommand) ProtoMessage() {}

func (x *AssignJobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJobCommand.ProtoReflect.Descriptor instead.
func (*AssignJobCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *AssignJobCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignJobCommand) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type CompleteJobCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Result        *JobResult             `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteJobCommand) Reset() {
	*x = CompleteJobCommand{}
	mi := &file_api_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteJobCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteJobCommand) ProtoMessage() {}

func (x *CompleteJobCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteJobCommand.ProtoReflect.Descriptor instead.
func (*CompleteJobCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteJobCommand) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteJobCommand) GetResult() *JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type RegisterWorkerCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxConcurrentJobs int32                  `protobuf:"varint,3,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterWorkerCommand) Reset() {
	*x = RegisterWorkerCommand{}
	mi := &file_api_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerCommand) ProtoMessage() {}

func (x *RegisterWorkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerCommand.ProtoReflect.Descriptor instead.
func (*RegisterWorkerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerCommand) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerCommand) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerCommand) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

type RemoveWorkerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWorkerCommand) Reset() {
	*x = RemoveWorkerCommand{}
	mi := &file_api_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWorkerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWorkerCommand) ProtoMessage() {}

func (x *RemoveWorkerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWorkerCommand.ProtoReflect.Descriptor instead.
func (*RemoveWorkerCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveWorkerCommand) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RemoveWorkerCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Snapshot data
type Snapshot struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Jobs          map[string]*Job            `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workers       map[string]*RaftWorkerInfo `protobuf:"bytes,2,rep,name=workers,proto3" json:"workers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastJobId     int64                      `protobuf:"varint,3,opt,name=last_job_id,json=lastJobId,proto3" json:"last_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_api_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *Snapshot) GetJobs() map[string]*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *Snapshot) GetWorkers() map[string]*RaftWorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *Snapshot) GetLastJobId() int64 {
	if x != nil {
		return x.LastJobId
	}
	return 0
}

type RaftWorkerInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxConcurrentJobs int32                  `protobuf:"varint,3,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	ActiveJobs        int32                  `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	LastHeartbeat     int64                  `protobuf:"varint,5,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"` // Unix timestamp
	Status            string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                     // "active", "inactive", "failed"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RaftWorkerInfo) Reset() {
	*x = RaftWorkerInfo{}
	mi := &file_api_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftWorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftWorkerInfo) ProtoMessage() {}

func (x *RaftWorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftWorkerInfo.ProtoReflect.Descriptor instead.
func (*RaftWorkerInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_raft_proto_rawDescGZIP(), []int{7}
}

func (x *RaftWorkerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftWorkerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RaftWorkerInfo) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *RaftWorkerInfo) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *RaftWorkerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

func (x *RaftWorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_raft_proto protoreflect.FileDescriptor

const file_api_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/raft.proto\x12\x05proto\x1a\x19api/proto/scheduler.proto\"7\n" +
	"\aCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"0\n" +
	"\x10SubmitJobCommand\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".proto.JobR\x03job\"F\n" +
	"\x10AssignJobCommand\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"U\n" +
	"\x12CompleteJobCommand\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12(\n" +
	"\x06result\x18\x02 \x01(\v2\x10.proto.JobResultR\x06result\"~\n" +
	"\x15RegisterWorkerCommand\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x13max_concurrent_jobs\x18\x03 \x01(\x05R\x11maxConcurrentJobs\"J\n" +
	"\x13RemoveWorkerCommand\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa9\x02\n" +
	"\bSnapshot\x12-\n" +
	"\x04jobs\x18\x01 \x03(\v2\x19.proto.Snapshot.JobsEntryR\x04jobs\x126\n" +
	"\aworkers\x18\x02 \x03(\v2\x1c.proto.Snapshot.WorkersEntryR\aworkers\x12\x1e\n" +
	"\vlast_job_id\x18\x03 \x01(\x03R\tlastJobId\x1aC\n" +
	"\tJobsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".proto.JobR\x05value:\x028\x01\x1aQ\n" +
	"\fWorkersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.proto.RaftWorkerInfoR\x05value:\x028\x01\"\xca\x01\n" +
	"\x0eRaftWorkerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x13max_concurrent_jobs\x18\x03 \x01(\x05R\x11maxConcurrentJobs\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x05R\n" +
	"activeJobs\x12%\n" +
	"\x0elast_heartbeat\x18\x05 \x01(\x03R\rlastHeartbeat\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06statusB1Z/github.com/francisco3ferraz/conductor/api/protob\x06proto3"

var (
	file_api_proto_raft_proto_rawDescOnce sync.Once
	file_api_proto_raft_proto_rawDescData []byte
)

func file_api_proto_raft_proto_rawDescGZIP() []byte {
	file_api_proto_raft_proto_rawDescOnce.Do(func() {
		file_api_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_raft_proto_rawDesc), len(file_api_proto_raft_proto_rawDesc)))
	})
	return file_api_proto_raft_proto_rawDescData
}

var file_api_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_raft_proto_goTypes = []any{
	(*Command)(nil),               // 0: proto.Command
	(*SubmitJobCommand)(nil),      // 1: proto.SubmitJobCommand
	(*AssignJobCommand)(nil),      // 2: proto.AssignJobCommand
	(*CompleteJobCommand)(nil),    // 3: proto.CompleteJobCommand
	(*RegisterWorkerCommand)(nil), // 4: proto.RegisterWorkerCommand
	(*RemoveWorkerCommand)(nil),   // 5: proto.RemoveWorkerCommand
	(*Snapshot)(nil),              // 6: proto.Snapshot
	(*RaftWorkerInfo)(nil),        // 7: proto.RaftWorkerInfo
	nil,                           // 8: proto.Snapshot.JobsEntry
	nil,                           // 9: proto.Snapshot.WorkersEntry
	(*Job)(nil),                   // 10: proto.Job
	(*JobResult)(nil),             // 11: proto.JobResult
}
var file_api_proto_raft_proto_depIdxs = []int32{
	10, // 0: proto.SubmitJobCommand.job:type_name -> proto.Job
	11, // 1: proto.CompleteJobCommand.result:type_name -> proto.JobResult
	8,  // 2: proto.Snapshot.jobs:type_name -> proto.Snapshot.JobsEntry
	9,  // 3: proto.Snapshot.workers:type_name -> proto.Snapshot.WorkersEntry
	10, // 4: proto.Snapshot.JobsEntry.value:type_name -> proto.Job
	7,  // 5: proto.Snapshot.WorkersEntry.value:type_name -> proto.RaftWorkerInfo
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_raft_proto_init() }
func file_api_proto_raft_proto_init() {
	if File_api_proto_raft_proto != nil {
		return
	}
	file_api_proto_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_raft_proto_rawDesc), len(file_api_proto_raft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_raft_proto_goTypes,
		DependencyIndexes: file_api_proto_raft_proto_depIdxs,
		MessageInfos:      file_api_proto_raft_proto_msgTypes,
	}.Build()
	File_api_proto_raft_proto = out.File
	file_api_proto_raft_proto_goTypes = nil
	file_api_proto_raft_proto_depIdxs = nil
}
