// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/scheduler.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job submission request
type SubmitJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                            // Job type: "image_processing", "web_scraping", "data_analysis"
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                                      // Job payload
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`                                   // Job priority (higher = more important)
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`             // Maximum retry attempts
	TimeoutSeconds int64                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Job timeout in seconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitJobRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *SubmitJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *SubmitJobRequest) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Job status query
type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// List jobs
type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter  string                 `protobuf:"bytes,1,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"` // Filter by status (optional)
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                  // Maximum number of jobs to return
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                                // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Cancel job
type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Job model
type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                           // "pending", "assigned", "running", "completed", "failed", "cancelled"
	AssignedTo     string                 `protobuf:"bytes,6,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // Worker ID
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Result         *JobResult             `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	RetryCount     int32                  `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,12,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,13,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TimeoutSeconds int64                  `protobuf:"varint,14,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Job timeout in seconds (0 = no timeout)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_api_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Job) GetResult() *JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Job) GetTimeoutSeconds() int64 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_api_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *JobResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JobResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// Cluster membership
type JoinClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // Raft bind address of joining node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{10}
}

func (x *JoinClusterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinClusterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type JoinClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Leader        string                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"` // Current leader address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterResponse) Reset() {
	*x = JoinClusterResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse) ProtoMessage() {}

func (x *JoinClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{11}
}

func (x *JoinClusterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinClusterResponse) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

// Worker communication messages (worker → master)
type RegisterWorkerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxConcurrentJobs int32                  `protobuf:"varint,3,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	Capabilities      map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Worker capabilities/tags
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *RegisterWorkerRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Stats         *WorkerStats           `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{14}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetStats() *WorkerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ack               bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	AssignedJobsCount int32                  `protobuf:"varint,2,opt,name=assigned_jobs_count,json=assignedJobsCount,proto3" json:"assigned_jobs_count,omitempty"` // Number of jobs assigned to this worker
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetAssignedJobsCount() int32 {
	if x != nil {
		return x.AssignedJobsCount
	}
	return 0
}

type WorkerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveJobs    int32                  `protobuf:"varint,1,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	CompletedJobs int32                  `protobuf:"varint,2,opt,name=completed_jobs,json=completedJobs,proto3" json:"completed_jobs,omitempty"`
	FailedJobs    int32                  `protobuf:"varint,3,opt,name=failed_jobs,json=failedJobs,proto3" json:"failed_jobs,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStats) Reset() {
	*x = WorkerStats{}
	mi := &file_api_proto_scheduler_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStats) ProtoMessage() {}

func (x *WorkerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStats.ProtoReflect.Descriptor instead.
func (*WorkerStats) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{16}
}

func (x *WorkerStats) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerStats) GetCompletedJobs() int32 {
	if x != nil {
		return x.CompletedJobs
	}
	return 0
}

func (x *WorkerStats) GetFailedJobs() int32 {
	if x != nil {
		return x.FailedJobs
	}
	return 0
}

func (x *WorkerStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerStats) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        *JobResult             `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{17}
}

func (x *ReportResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetResult() *JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{18}
}

func (x *ReportResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Dead Letter Queue operations
type ListDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`   // Maximum number of jobs to return
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // Pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQRequest) Reset() {
	*x = ListDLQRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQRequest) ProtoMessage() {}

func (x *ListDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQRequest.ProtoReflect.Descriptor instead.
func (*ListDLQRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{19}
}

func (x *ListDLQRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDLQRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQResponse) Reset() {
	*x = ListDLQResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQResponse) ProtoMessage() {}

func (x *ListDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQResponse.ProtoReflect.Descriptor instead.
func (*ListDLQResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{20}
}

func (x *ListDLQResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListDLQResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RetryFromDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFromDLQRequest) Reset() {
	*x = RetryFromDLQRequest{}
	mi := &file_api_proto_scheduler_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFromDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFromDLQRequest) ProtoMessage() {}

func (x *RetryFromDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFromDLQRequest.ProtoReflect.Descriptor instead.
func (*RetryFromDLQRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{21}
}

func (x *RetryFromDLQRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RetryFromDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFromDLQResponse) Reset() {
	*x = RetryFromDLQResponse{}
	mi := &file_api_proto_scheduler_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFromDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFromDLQResponse) ProtoMessage() {}

func (x *RetryFromDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_scheduler_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFromDLQResponse.ProtoReflect.Descriptor instead.
func (*RetryFromDLQResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_scheduler_proto_rawDescGZIP(), []int{22}
}

func (x *RetryFromDLQResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RetryFromDLQResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_scheduler_proto protoreflect.FileDescriptor

const file_api_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/scheduler.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x01\n" +
	"\x10SubmitJobRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x03R\x0etimeoutSeconds\"\\\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"4\n" +
	"\x14GetJobStatusResponse\x12\x1c\n" +
	"\x03job\x18\x01 \x01(\v2\n" +
	".proto.JobR\x03job\"d\n" +
	"\x0fListJobsRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x01(\tR\fstatusFilter\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"H\n" +
	"\x10ListJobsResponse\x12\x1e\n" +
	"\x04jobs\x18\x01 \x03(\v2\n" +
	".proto.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"G\n" +
	"\x11CancelJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x87\x04\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\x06 \x01(\tR\n" +
	"assignedTo\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12(\n" +
	"\x06result\x18\n" +
	" \x01(\v2\x10.proto.JobResultR\x06result\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\f \x01(\x05R\n" +
	"maxRetries\x12#\n" +
	"\rerror_message\x18\r \x01(\tR\ferrorMessage\x12'\n" +
	"\x0ftimeout_seconds\x18\x0e \x01(\x03R\x0etimeoutSeconds\"t\n" +
	"\tJobResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\"G\n" +
	"\x12JoinClusterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"a\n" +
	"\x13JoinClusterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\"\x93\x02\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x13max_concurrent_jobs\x18\x03 \x01(\x05R\x11maxConcurrentJobs\x12R\n" +
	"\fcapabilities\x18\x04 \x03(\v2..proto.RegisterWorkerRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12(\n" +
	"\x05stats\x18\x02 \x01(\v2\x12.proto.WorkerStatsR\x05stats\"U\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12.\n" +
	"\x13assigned_jobs_count\x18\x02 \x01(\x05R\x11assignedJobsCount\"\xb6\x01\n" +
	"\vWorkerStats\x12\x1f\n" +
	"\vactive_jobs\x18\x01 \x01(\x05R\n" +
	"activeJobs\x12%\n" +
	"\x0ecompleted_jobs\x18\x02 \x01(\x05R\rcompletedJobs\x12\x1f\n" +
	"\vfailed_jobs\x18\x03 \x01(\x05R\n" +
	"failedJobs\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"s\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12(\n" +
	"\x06result\x18\x03 \x01(\v2\x10.proto.JobResultR\x06result\"J\n" +
	"\x14ReportResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x0eListDLQRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"G\n" +
	"\x0fListDLQResponse\x12\x1e\n" +
	"\x04jobs\x18\x01 \x03(\v2\n" +
	".proto.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x13RetryFromDLQRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"J\n" +
	"\x14RetryFromDLQResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb6\x05\n" +
	"\rMasterService\x12>\n" +
	"\tSubmitJob\x12\x17.proto.SubmitJobRequest\x1a\x18.proto.SubmitJobResponse\x12G\n" +
	"\fGetJobStatus\x12\x1a.proto.GetJobStatusRequest\x1a\x1b.proto.GetJobStatusResponse\x12;\n" +
	"\bListJobs\x12\x16.proto.ListJobsRequest\x1a\x17.proto.ListJobsResponse\x12>\n" +
	"\tCancelJob\x12\x17.proto.CancelJobRequest\x1a\x18.proto.CancelJobResponse\x12D\n" +
	"\vJoinCluster\x12\x19.proto.JoinClusterRequest\x1a\x1a.proto.JoinClusterResponse\x12M\n" +
	"\x0eRegisterWorker\x12\x1c.proto.RegisterWorkerRequest\x1a\x1d.proto.RegisterWorkerResponse\x12>\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponse\x12G\n" +
	"\fReportResult\x12\x1a.proto.ReportResultRequest\x1a\x1b.proto.ReportResultResponse\x128\n" +
	"\aListDLQ\x12\x15.proto.ListDLQRequest\x1a\x16.proto.ListDLQResponse\x12G\n" +
	"\fRetryFromDLQ\x12\x1a.proto.RetryFromDLQRequest\x1a\x1b.proto.RetryFromDLQResponseB1Z/github.com/francisco3ferraz/conductor/api/protob\x06proto3"

var (
	file_api_proto_scheduler_proto_rawDescOnce sync.Once
	file_api_proto_scheduler_proto_rawDescData []byte
)

func file_api_proto_scheduler_proto_rawDescGZIP() []byte {
	file_api_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_api_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)))
	})
	return file_api_proto_scheduler_proto_rawDescData
}

var file_api_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_scheduler_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),       // 0: proto.SubmitJobRequest
	(*SubmitJobResponse)(nil),      // 1: proto.SubmitJobResponse
	(*GetJobStatusRequest)(nil),    // 2: proto.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),   // 3: proto.GetJobStatusResponse
	(*ListJobsRequest)(nil),        // 4: proto.ListJobsRequest
	(*ListJobsResponse)(nil),       // 5: proto.ListJobsResponse
	(*CancelJobRequest)(nil),       // 6: proto.CancelJobRequest
	(*CancelJobResponse)(nil),      // 7: proto.CancelJobResponse
	(*Job)(nil),                    // 8: proto.Job
	(*JobResult)(nil),              // 9: proto.JobResult
	(*JoinClusterRequest)(nil),     // 10: proto.JoinClusterRequest
	(*JoinClusterResponse)(nil),    // 11: proto.JoinClusterResponse
	(*RegisterWorkerRequest)(nil),  // 12: proto.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 13: proto.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 14: proto.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 15: proto.HeartbeatResponse
	(*WorkerStats)(nil),            // 16: proto.WorkerStats
	(*ReportResultRequest)(nil),    // 17: proto.ReportResultRequest
	(*ReportResultResponse)(nil),   // 18: proto.ReportResultResponse
	(*ListDLQRequest)(nil),         // 19: proto.ListDLQRequest
	(*ListDLQResponse)(nil),        // 20: proto.ListDLQResponse
	(*RetryFromDLQRequest)(nil),    // 21: proto.RetryFromDLQRequest
	(*RetryFromDLQResponse)(nil),   // 22: proto.RetryFromDLQResponse
	nil,                            // 23: proto.RegisterWorkerRequest.CapabilitiesEntry
	(*timestamppb.Timestamp)(nil),  // 24: google.protobuf.Timestamp
}
var file_api_proto_scheduler_proto_depIdxs = []int32{
	8,  // 0: proto.GetJobStatusResponse.job:type_name -> proto.Job
	8,  // 1: proto.ListJobsResponse.jobs:type_name -> proto.Job
	24, // 2: proto.Job.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: proto.Job.started_at:type_name -> google.protobuf.Timestamp
	24, // 4: proto.Job.completed_at:type_name -> google.protobuf.Timestamp
	9,  // 5: proto.Job.result:type_name -> proto.JobResult
	23, // 6: proto.RegisterWorkerRequest.capabilities:type_name -> proto.RegisterWorkerRequest.CapabilitiesEntry
	16, // 7: proto.HeartbeatRequest.stats:type_name -> proto.WorkerStats
	9,  // 8: proto.ReportResultRequest.result:type_name -> proto.JobResult
	8,  // 9: proto.ListDLQResponse.jobs:type_name -> proto.Job
	0,  // 10: proto.MasterService.SubmitJob:input_type -> proto.SubmitJobRequest
	2,  // 11: proto.MasterService.GetJobStatus:input_type -> proto.GetJobStatusRequest
	4,  // 12: proto.MasterService.ListJobs:input_type -> proto.ListJobsRequest
	6,  // 13: proto.MasterService.CancelJob:input_type -> proto.CancelJobRequest
	10, // 14: proto.MasterService.JoinCluster:input_type -> proto.JoinClusterRequest
	12, // 15: proto.MasterService.RegisterWorker:input_type -> proto.RegisterWorkerRequest
	14, // 16: proto.MasterService.Heartbeat:input_type -> proto.HeartbeatRequest
	17, // 17: proto.MasterService.ReportResult:input_type -> proto.ReportResultRequest
	19, // 18: proto.MasterService.ListDLQ:input_type -> proto.ListDLQRequest
	21, // 19: proto.MasterService.RetryFromDLQ:input_type -> proto.RetryFromDLQRequest
	1,  // 20: proto.MasterService.SubmitJob:output_type -> proto.SubmitJobResponse
	3,  // 21: proto.MasterService.GetJobStatus:output_type -> proto.GetJobStatusResponse
	5,  // 22: proto.MasterService.ListJobs:output_type -> proto.ListJobsResponse
	7,  // 23: proto.MasterService.CancelJob:output_type -> proto.CancelJobResponse
	11, // 24: proto.MasterService.JoinCluster:output_type -> proto.JoinClusterResponse
	13, // 25: proto.MasterService.RegisterWorker:output_type -> proto.RegisterWorkerResponse
	15, // 26: proto.MasterService.Heartbeat:output_type -> proto.HeartbeatResponse
	18, // 27: proto.MasterService.ReportResult:output_type -> proto.ReportResultResponse
	20, // 28: proto.MasterService.ListDLQ:output_type -> proto.ListDLQResponse
	22, // 29: proto.MasterService.RetryFromDLQ:output_type -> proto.RetryFromDLQResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_scheduler_proto_init() }
func file_api_proto_scheduler_proto_init() {
	if File_api_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_scheduler_proto_rawDesc), len(file_api_proto_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_api_proto_scheduler_proto_depIdxs,
		MessageInfos:      file_api_proto_scheduler_proto_msgTypes,
	}.Build()
	File_api_proto_scheduler_proto = out.File
	file_api_proto_scheduler_proto_goTypes = nil
	file_api_proto_scheduler_proto_depIdxs = nil
}
