// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Worker registration
type RegisterWorkerRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkerId          string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxConcurrentJobs int32                  `protobuf:"varint,3,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	Capabilities      map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Worker capabilities/tags
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *RegisterWorkerRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_api_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Stats         *WorkerStats           `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetStats() *WorkerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type HeartbeatResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Ack               bool                   `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	AssignedJobsCount int32                  `protobuf:"varint,2,opt,name=assigned_jobs_count,json=assignedJobsCount,proto3" json:"assigned_jobs_count,omitempty"` // Number of jobs assigned to this worker
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *HeartbeatResponse) GetAssignedJobsCount() int32 {
	if x != nil {
		return x.AssignedJobsCount
	}
	return 0
}

type WorkerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveJobs    int32                  `protobuf:"varint,1,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	CompletedJobs int32                  `protobuf:"varint,2,opt,name=completed_jobs,json=completedJobs,proto3" json:"completed_jobs,omitempty"`
	FailedJobs    int32                  `protobuf:"varint,3,opt,name=failed_jobs,json=failedJobs,proto3" json:"failed_jobs,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,4,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,5,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStats) Reset() {
	*x = WorkerStats{}
	mi := &file_api_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStats) ProtoMessage() {}

func (x *WorkerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStats.ProtoReflect.Descriptor instead.
func (*WorkerStats) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStats) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerStats) GetCompletedJobs() int32 {
	if x != nil {
		return x.CompletedJobs
	}
	return 0
}

func (x *WorkerStats) GetFailedJobs() int32 {
	if x != nil {
		return x.FailedJobs
	}
	return 0
}

func (x *WorkerStats) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *WorkerStats) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

// Job assignment from master to worker
type AssignJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJobRequest) Reset() {
	*x = AssignJobRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJobRequest) ProtoMessage() {}

func (x *AssignJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJobRequest.ProtoReflect.Descriptor instead.
func (*AssignJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *AssignJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssignJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type AssignJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJobResponse) Reset() {
	*x = AssignJobResponse{}
	mi := &file_api_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJobResponse) ProtoMessage() {}

func (x *AssignJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJobResponse.ProtoReflect.Descriptor instead.
func (*AssignJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *AssignJobResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Report job result from worker to master
type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        *JobResult             `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *ReportResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ReportResultRequest) GetResult() *JobResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_api_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_worker_proto protoreflect.FileDescriptor

const file_api_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/worker.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19api/proto/scheduler.proto\"\x93\x02\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12.\n" +
	"\x13max_concurrent_jobs\x18\x03 \x01(\x05R\x11maxConcurrentJobs\x12R\n" +
	"\fcapabilities\x18\x04 \x03(\v2..proto.RegisterWorkerRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12(\n" +
	"\x05stats\x18\x02 \x01(\v2\x12.proto.WorkerStatsR\x05stats\"U\n" +
	"\x11HeartbeatResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\bR\x03ack\x12.\n" +
	"\x13assigned_jobs_count\x18\x02 \x01(\x05R\x11assignedJobsCount\"\xb6\x01\n" +
	"\vWorkerStats\x12\x1f\n" +
	"\vactive_jobs\x18\x01 \x01(\x05R\n" +
	"activeJobs\x12%\n" +
	"\x0ecompleted_jobs\x18\x02 \x01(\x05R\rcompletedJobs\x12\x1f\n" +
	"\vfailed_jobs\x18\x03 \x01(\x05R\n" +
	"failedJobs\x12\x1b\n" +
	"\tcpu_usage\x18\x04 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x05 \x01(\x01R\vmemoryUsage\"M\n" +
	"\x10AssignJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\x03job\x18\x02 \x01(\v2\n" +
	".proto.JobR\x03job\"I\n" +
	"\x11AssignJobResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x13ReportResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12(\n" +
	"\x06result\x18\x03 \x01(\v2\x10.proto.JobResultR\x06result\"J\n" +
	"\x14ReportResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa7\x02\n" +
	"\rWorkerService\x12M\n" +
	"\x0eRegisterWorker\x12\x1c.proto.RegisterWorkerRequest\x1a\x1d.proto.RegisterWorkerResponse\x12>\n" +
	"\tHeartbeat\x12\x17.proto.HeartbeatRequest\x1a\x18.proto.HeartbeatResponse\x12>\n" +
	"\tAssignJob\x12\x17.proto.AssignJobRequest\x1a\x18.proto.AssignJobResponse\x12G\n" +
	"\fReportResult\x12\x1a.proto.ReportResultRequest\x1a\x1b.proto.ReportResultResponseB1Z/github.com/francisco3ferraz/conductor/api/protob\x06proto3"

var (
	file_api_proto_worker_proto_rawDescOnce sync.Once
	file_api_proto_worker_proto_rawDescData []byte
)

func file_api_proto_worker_proto_rawDescGZIP() []byte {
	file_api_proto_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)))
	})
	return file_api_proto_worker_proto_rawDescData
}

var file_api_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_worker_proto_goTypes = []any{
	(*RegisterWorkerRequest)(nil),  // 0: proto.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 1: proto.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 2: proto.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 3: proto.HeartbeatResponse
	(*WorkerStats)(nil),            // 4: proto.WorkerStats
	(*AssignJobRequest)(nil),       // 5: proto.AssignJobRequest
	(*AssignJobResponse)(nil),      // 6: proto.AssignJobResponse
	(*ReportResultRequest)(nil),    // 7: proto.ReportResultRequest
	(*ReportResultResponse)(nil),   // 8: proto.ReportResultResponse
	nil,                            // 9: proto.RegisterWorkerRequest.CapabilitiesEntry
	(*Job)(nil),                    // 10: proto.Job
	(*JobResult)(nil),              // 11: proto.JobResult
}
var file_api_proto_worker_proto_depIdxs = []int32{
	9,  // 0: proto.RegisterWorkerRequest.capabilities:type_name -> proto.RegisterWorkerRequest.CapabilitiesEntry
	4,  // 1: proto.HeartbeatRequest.stats:type_name -> proto.WorkerStats
	10, // 2: proto.AssignJobRequest.job:type_name -> proto.Job
	11, // 3: proto.ReportResultRequest.result:type_name -> proto.JobResult
	0,  // 4: proto.WorkerService.RegisterWorker:input_type -> proto.RegisterWorkerRequest
	2,  // 5: proto.WorkerService.Heartbeat:input_type -> proto.HeartbeatRequest
	5,  // 6: proto.WorkerService.AssignJob:input_type -> proto.AssignJobRequest
	7,  // 7: proto.WorkerService.ReportResult:input_type -> proto.ReportResultRequest
	1,  // 8: proto.WorkerService.RegisterWorker:output_type -> proto.RegisterWorkerResponse
	3,  // 9: proto.WorkerService.Heartbeat:output_type -> proto.HeartbeatResponse
	6,  // 10: proto.WorkerService.AssignJob:output_type -> proto.AssignJobResponse
	8,  // 11: proto.WorkerService.ReportResult:output_type -> proto.ReportResultResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_worker_proto_init() }
func file_api_proto_worker_proto_init() {
	if File_api_proto_worker_proto != nil {
		return
	}
	file_api_proto_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_worker_proto_depIdxs,
		MessageInfos:      file_api_proto_worker_proto_msgTypes,
	}.Build()
	File_api_proto_worker_proto = out.File
	file_api_proto_worker_proto_goTypes = nil
	file_api_proto_worker_proto_depIdxs = nil
}
