// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job assignment from master to worker
type AssignJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Job           *Job                   `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJobRequest) Reset() {
	*x = AssignJobRequest{}
	mi := &file_api_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJobRequest) ProtoMessage() {}

func (x *AssignJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJobRequest.ProtoReflect.Descriptor instead.
func (*AssignJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *AssignJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssignJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type AssignJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJobResponse) Reset() {
	*x = AssignJobResponse{}
	mi := &file_api_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJobResponse) ProtoMessage() {}

func (x *AssignJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJobResponse.ProtoReflect.Descriptor instead.
func (*AssignJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *AssignJobResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *AssignJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_worker_proto protoreflect.FileDescriptor

const file_api_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/worker.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19api/proto/scheduler.proto\"M\n" +
	"\x10AssignJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\x03job\x18\x02 \x01(\v2\n" +
	".proto.JobR\x03job\"I\n" +
	"\x11AssignJobResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2O\n" +
	"\rWorkerService\x12>\n" +
	"\tAssignJob\x12\x17.proto.AssignJobRequest\x1a\x18.proto.AssignJobResponseB1Z/github.com/francisco3ferraz/conductor/api/protob\x06proto3"

var (
	file_api_proto_worker_proto_rawDescOnce sync.Once
	file_api_proto_worker_proto_rawDescData []byte
)

func file_api_proto_worker_proto_rawDescGZIP() []byte {
	file_api_proto_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)))
	})
	return file_api_proto_worker_proto_rawDescData
}

var file_api_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_worker_proto_goTypes = []any{
	(*AssignJobRequest)(nil),  // 0: proto.AssignJobRequest
	(*AssignJobResponse)(nil), // 1: proto.AssignJobResponse
	(*Job)(nil),               // 2: proto.Job
}
var file_api_proto_worker_proto_depIdxs = []int32{
	2, // 0: proto.AssignJobRequest.job:type_name -> proto.Job
	0, // 1: proto.WorkerService.AssignJob:input_type -> proto.AssignJobRequest
	1, // 2: proto.WorkerService.AssignJob:output_type -> proto.AssignJobResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_worker_proto_init() }
func file_api_proto_worker_proto_init() {
	if File_api_proto_worker_proto != nil {
		return
	}
	file_api_proto_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_worker_proto_rawDesc), len(file_api_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_worker_proto_depIdxs,
		MessageInfos:      file_api_proto_worker_proto_msgTypes,
	}.Build()
	File_api_proto_worker_proto = out.File
	file_api_proto_worker_proto_goTypes = nil
	file_api_proto_worker_proto_depIdxs = nil
}
